const config = {
  AUTH_SERVICE_CONNECTED_SERVICE_ID:
    process.env.AUTH_SERVICE_CONNECTED_SERVICE_ID!,
  AUTH_SERVICE_HOST_URL: process.env.AUTH_SERVICE_HOST_URL!,
  SITE_URL: process.env.SITE_URL!,
  SITE_UNAUTHORIZED_URL: process.env.SITE_UNAUTHORIZED_URL!,
  SITE_LOGIN_URL: process.env.SITE_LOGIN_URL!,
  AUTH_POST_LOGOUT_REDIRECT: process.env.AUTH_POST_LOGOUT_REDIRECT!,
  PUBLIC_ROUTE_PERMISSION: process.env.PUBLIC_ROUTE_PERMISSION || 'public',
} as const;

export default config;
